version: '3'

services:
  code:
    image: codercom/code-server:latest
    container_name: devguerrilla
    ports:
      - "8081:8080"
    volumes:
      - ./:/home/coder/project
    environment:
      - PASSWORD=199811  
